name: Wikimedia Archive

on:
  workflow_dispatch:
    inputs:
      item-number:
        description: 'Item number'
        required: true

jobs:
  archive_commons_items:
    runs-on: ubuntu-latest

    steps:
    - name: Archive Wikimedia Commons Items
      run: |
        start_number=${{ github.event.inputs.item-number }}
        i=$start_number

        api_url="https://commons.wikimedia.org/w/api.php?action=query&format=json&prop=imageinfo&iiprop=url&pageids=$i"

        # Echo the API URL
        echo "API URL: $api_url"

        # Retrieve information about the item and suppress output
        response=$(curl -sS $api_url)

        # Extract and archive descriptionurl
        description_url=$(echo $response | jq -r '.query.pages.'$i'.imageinfo[0].descriptionurl' || true)
        [ -n "$description_url" ] && echo "Description URL: $description_url" && curl -sS "https://web.archive.org/save/$description_url" > /dev/null || true

        # Extract and archive outlinks
        outlinks=$(echo $response | jq -r '.query.pages.'$i'.imageinfo[0].metadata[] | select(.name == "commonswiki" and .value != "") | .value' || true)
        IFS=$'\n' # Set Internal Field Separator to newline
        for outlink in $outlinks; do
          echo "Outlink: $outlink" && curl -sS "https://web.archive.org/save/$outlink" > /dev/null || true
        done

        # Extract and archive descriptionshorturl
        description_shorturl=$(echo $response | jq -r '.query.pages.'$i'.imageinfo[0].descriptionshorturl' || true)
        [ -n "$description_shorturl" ] && echo "Description Short URL: $description_shorturl" && curl -sS "https://web.archive.org/save/$description_shorturl" > /dev/null || true

        # Extract and archive image URL
        image_url=$(echo $response | jq -r '.query.pages.'$i'.imageinfo[0].url' || true)
        [ -n "$image_url" ] && echo "Image URL: $image_url" && curl -sS "https://web.archive.org/save/$image_url" > /dev/null || true

        # Archive the original Wikimedia Commons item page URL
        item_page_url="https://commons.wikimedia.org/w/index.php?curid=$i"
        echo "Item Page URL: $item_page_url" && curl -sS "https://web.archive.org/save/$item_page_url" > /dev/null || true

        # Archive the API URL
        echo "API URL: $api_url" && curl -sS "https://web.archive.org/save/$api_url" > /dev/null || true
      continue-on-error: true
