name: Wikimedia Archive

on:
  workflow_dispatch:
    inputs:
      item-number:
        description: 'Item number'
        required: true

jobs:
  archive_commons_items:
    runs-on: ubuntu-latest

    steps:
    - name: Archive Wikimedia Commons Items
      run: |
        start_number=${{ github.event.inputs.item-number }}
        i=$start_number

        api_url="https://commons.wikimedia.org/w/api.php?action=query&format=json&prop=imageinfo&iiprop=url&pageids=$i"

        # Retrieve information about the item and suppress output
        response=$(curl -sS $api_url)

        # Echo the descriptionurl and Archive it
        description_url=$(echo $response | grep -oP '"descriptionurl":"\K[^"]+' || true)
        [ -n "$description_url" ] && echo $description_url && curl -sS "https://web.archive.org/save/$description_url" > /dev/null || true

        # Echo each outlink and Archive it
        outlinks=$(echo $response | grep -oP '"href":"\K[^"]+' | grep -v "^http" || true)
        for outlink in $outlinks; do
          echo $outlink && curl -sS "https://web.archive.org/save/$outlink" > /dev/null || true
        done

        # Echo the descriptionshorturl and Archive it
        description_shorturl=$(echo $response | grep -oP '"descriptionshorturl":"\K[^"]+' || true)
        [ -n "$description_shorturl" ] && echo $description_shorturl && curl -sS "https://web.archive.org/save/$description_shorturl" > /dev/null || true

        # Echo the image URL and Archive it
        image_url=$(echo $response | grep -oP '"url":"\K[^"]+' || true)
        [ -n "$image_url" ] && echo $image_url && curl -sS "https://web.archive.org/save/$image_url" > /dev/null || true

        # Echo the original Wikimedia Commons item page URL and Archive it
        item_page_url="https://commons.wikimedia.org/w/index.php?curid=$i"
        echo $item_page_url && curl -sS "https://web.archive.org/save/$item_page_url" > /dev/null || true

        # Echo the API URL and Archive it
        echo $api_url && curl -sS "https://web.archive.org/save/$api_url" > /dev/null || true
      continue-on-error: true
