name: Wikimedia Archive

on:
  workflow_dispatch:
    inputs:
      start-number:
        description: 'Start number for Wikimedia Commons items'
        required: true

jobs:
  archive_commons_items:
    runs-on: ubuntu-latest

    steps:
    - name: Archive Wikimedia Commons Items
      run: |
        start_number=${{ github.event.inputs.start-number }}

        for ((i = $start_number; i < $start_number + 10; i++)); do

          api_url="https://commons.wikimedia.org/w/api.php?action=query&format=json&prop=imageinfo&iiprop=url&pageids=$i"

          # Retrieve information about the item and suppress output
          response=$(curl -sS $api_url)

          # Extract descriptionurl
          description_url=$(echo $response | grep -oP '"descriptionurl":"\K[^"]+' || true)

          # Archive the descriptionurl and suppress output
          if [ -n "$description_url" ]; then
            curl -sS "https://web.archive.org/save/$description_url" > /dev/null || true
          fi

          # Extract outlinks
          outlinks=$(echo $response | grep -oP '"href":"\K[^"]+' | grep -v "^http" || true)

          # Archive each outlink and suppress output
          for outlink in $outlinks; do
            curl -sS "https://web.archive.org/save/$outlink" > /dev/null || true
          done

          # Archive descriptionshorturl and suppress output
          description_shorturl=$(echo $response | grep -oP '"descriptionshorturl":"\K[^"]+' || true)
          if [ -n "$description_shorturl" ]; then
            curl -sS "https://web.archive.org/save/$description_shorturl" > /dev/null || true
          fi

          # Archive the image URL and suppress output
          image_url=$(echo $response | grep -oP '"url":"\K[^"]+' || true)
          if [ -n "$image_url" ]; then
            curl -sS "https://web.archive.org/save/$image_url" > /dev/null || true
          fi

          # Archive the original Wikimedia Commons item page and suppress output
          curl -sS "https://web.archive.org/save/https://commons.wikimedia.org/w/index.php?curid=$i" > /dev/null || true

          # Archive the API URL and suppress output
          curl -sS "https://web.archive.org/save/$api_url" > /dev/null || true
        done
      continue-on-error: true
